CREATE TABLE mailing (

  id INTEGER AUTO_INCREMENT,
  name VARCHAR(100) UNIQUE DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  username VARCHAR(100) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;