apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailing-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailing
  template:
    metadata:
      labels:
        app: mailing
    spec:
      containers:
        - name: mailing
          image: davidhume/mailing
          ports:
            - containerPort: 8080
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: dbhost-secret
                  key: db_host
            - name: DB_NAME
              value: mailing_mc
            - name: DB_USERNAME
              value: root

---
apiVersion: v1
kind: Service
metadata:
  name: mailing-srv
spec:
  selector:
    app: mailing
  ports:
    - name: mailing
      protocol: TCP
      port: 8080
      targetPort: 8080
