apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeout-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeout
  template:
    metadata:
      labels:
        app: timeout
    spec:
      containers:
        - name: timeout
          image: davidhume/timeout
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: thedreamplace
            - name: REDIS_HOST
              value: timeout-redis-srv
